/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Computer_Comrade;

import java.awt.Color;
import java.awt.Desktop;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Prem Kumar Mehta
 * @author Bishal Kumar Sardar
 * @author Yogesh Dahal
 */
public class ComputerComradeInfo extends javax.swing.JFrame {
    
    private ArrayList<ComputerComrade> tData = new ArrayList();

    /**
     * Creates new form ComputerComradeInfo
     */
    public ComputerComradeInfo() {
        initComponents();
        jMainPanel.setVisible(false);
        jLoginPanel.setVisible(true);
    }

    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLoginPanel = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        txtPassword = new javax.swing.JTextField();
        btnLogin = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        btnHint = new javax.swing.JButton();
        jMainPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanelTable = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblInfo = new javax.swing.JTable();
        jPanelAdd = new javax.swing.JPanel();
        txtName = new javax.swing.JTextField();
        txtPrice = new javax.swing.JTextField();
        cbCategory = new javax.swing.JComboBox<>();
        lblModelNumber = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        lblCategory = new javax.swing.JLabel();
        lblRange = new javax.swing.JLabel();
        lblPrice = new javax.swing.JLabel();
        lblDiscount = new javax.swing.JLabel();
        rbtnLow = new javax.swing.JRadioButton();
        txtModelNumber = new javax.swing.JTextField();
        rbtnMedium = new javax.swing.JRadioButton();
        rbtnHigh = new javax.swing.JRadioButton();
        btnAdd = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        cbDiscount = new javax.swing.JComboBox<>();
        jPanelSearch = new javax.swing.JPanel();
        jPanelSearchByItem = new javax.swing.JPanel();
        cbSearchByCategory = new javax.swing.JComboBox<>();
        btnSearchByCategory = new javax.swing.JButton();
        jPanelSearchByPrice = new javax.swing.JPanel();
        txtSearchByPrice = new javax.swing.JTextField();
        btnSearchByPrice = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jBackgroundPanel = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        miOpen = new javax.swing.JMenuItem();
        miSave = new javax.swing.JMenuItem();
        miImport = new javax.swing.JMenuItem();
        miExit = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);

        jLoginPanel.setBackground(new java.awt.Color(255, 255, 255));
        jLoginPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("French Script MT", 0, 30)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(90, 20, 168));
        jLabel4.setText("Tommorow Starts Here");
        jLoginPanel.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 100, -1, -1));

        txtUsername.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtUsername.setForeground(new java.awt.Color(204, 204, 204));
        txtUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsernameActionPerformed(evt);
            }
        });
        jLoginPanel.add(txtUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 380, 225, 39));

        txtPassword.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtPassword.setForeground(new java.awt.Color(204, 204, 204));
        txtPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPasswordActionPerformed(evt);
            }
        });
        jLoginPanel.add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 460, 225, 39));

        btnLogin.setBackground(new java.awt.Color(90, 20, 168));
        btnLogin.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnLogin.setForeground(new java.awt.Color(255, 255, 255));
        btnLogin.setText("LOGIN");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        jLoginPanel.add(btnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 530, 125, 37));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Computer_Comrade/logo.png"))); // NOI18N
        jLoginPanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 13, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(90, 20, 168));
        jLabel7.setText("Computer Comrade");
        jLoginPanel.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 20, 470, 90));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Computer_Comrade/23.jpg"))); // NOI18N
        jLoginPanel.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 128, -1, 555));

        jLabel6.setForeground(new java.awt.Color(102, 51, 255));
        jLabel6.setText("@ 2021 Working Sign In. All rights reserved | Computer Comrade Pvt. Ltd.");
        jLoginPanel.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 680, -1, 20));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Computer_Comrade/5340287_man_people_person_user_users_icon.png"))); // NOI18N
        jLoginPanel.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(888, 379, -1, 39));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Computer_Comrade/8201356_lock_password_padlock_privacy_ui_icon.png"))); // NOI18N
        jLoginPanel.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(888, 458, -1, 39));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(90, 20, 168));
        jLabel11.setText("Password");
        jLoginPanel.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 440, -1, -1));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(90, 20, 168));
        jLabel13.setText("Username");
        jLoginPanel.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 360, -1, -1));

        btnHint.setBackground(new java.awt.Color(255, 255, 255));
        btnHint.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        btnHint.setForeground(new java.awt.Color(90, 20, 168));
        btnHint.setText("show username & password");
        btnHint.setBorder(null);
        btnHint.setBorderPainted(false);
        btnHint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHintActionPerformed(evt);
            }
        });
        jLoginPanel.add(btnHint, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 500, 150, 20));

        jMainPanel.setBackground(new java.awt.Color(255, 255, 255));
        jMainPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Computer_Comrade/logo.png"))); // NOI18N
        jMainPanel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 95, 90));

        jLabel3.setBackground(new java.awt.Color(0, 51, 51));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(99, 20, 168));
        jLabel3.setText("Computer Comrade Information System");
        jMainPanel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 20, -1, -1));

        jPanelTable.setBackground(new java.awt.Color(255, 255, 255));
        jPanelTable.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Computer Comrade Information System", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N
        jPanelTable.setOpaque(false);

        tblInfo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Model Number", "Name", "Category", "Range", "Price", "Discount"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblInfo.setSelectionBackground(new java.awt.Color(204, 204, 204));
        tblInfo.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tblInfo);

        javax.swing.GroupLayout jPanelTableLayout = new javax.swing.GroupLayout(jPanelTable);
        jPanelTable.setLayout(jPanelTableLayout);
        jPanelTableLayout.setHorizontalGroup(
            jPanelTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1178, Short.MAX_VALUE)
        );
        jPanelTableLayout.setVerticalGroup(
            jPanelTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 231, Short.MAX_VALUE)
        );

        jMainPanel.add(jPanelTable, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 1190, 260));

        jPanelAdd.setBackground(java.awt.SystemColor.window);
        jPanelAdd.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(90, 20, 168), 2), "Add", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N

        txtName.setForeground(new java.awt.Color(153, 153, 153));
        txtName.setText("Enter Name");
        txtName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtNameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNameFocusLost(evt);
            }
        });

        txtPrice.setForeground(new java.awt.Color(153, 153, 153));
        txtPrice.setText("Enter Price");
        txtPrice.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtPriceFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtPriceFocusLost(evt);
            }
        });
        txtPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPriceActionPerformed(evt);
            }
        });
        txtPrice.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPriceKeyTyped(evt);
            }
        });

        cbCategory.setBackground(new java.awt.Color(90, 20, 168));
        cbCategory.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        cbCategory.setForeground(new java.awt.Color(255, 255, 255));
        cbCategory.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Keyboard", "Mouse", "Monitor", "Speaker", "Graphics Card", "RAM", "SSD", "HDD" }));

        lblModelNumber.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblModelNumber.setText("Model Number:");

        lblName.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblName.setText("Name:");

        lblCategory.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblCategory.setText("Category:");

        lblRange.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblRange.setText("Range");

        lblPrice.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblPrice.setText("Price:");

        lblDiscount.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblDiscount.setText("Discount:");

        rbtnLow.setBackground(java.awt.SystemColor.window);
        buttonGroup1.add(rbtnLow);
        rbtnLow.setSelected(true);
        rbtnLow.setText("Low");

        txtModelNumber.setForeground(new java.awt.Color(153, 153, 153));
        txtModelNumber.setText("Enter Model Number");
        txtModelNumber.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtModelNumberFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtModelNumberFocusLost(evt);
            }
        });

        rbtnMedium.setBackground(java.awt.SystemColor.window);
        buttonGroup1.add(rbtnMedium);
        rbtnMedium.setText("Medium");

        rbtnHigh.setBackground(java.awt.SystemColor.window);
        buttonGroup1.add(rbtnHigh);
        rbtnHigh.setText("High");

        btnAdd.setBackground(new java.awt.Color(90, 20, 168));
        btnAdd.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnAdd.setForeground(new java.awt.Color(255, 255, 255));
        btnAdd.setText("Add");
        btnAdd.setPreferredSize(new java.awt.Dimension(70, 31));
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnClear.setBackground(new java.awt.Color(90, 20, 168));
        btnClear.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnClear.setForeground(new java.awt.Color(255, 255, 255));
        btnClear.setText("Clear");
        btnClear.setPreferredSize(new java.awt.Dimension(61, 27));
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        cbDiscount.setBackground(new java.awt.Color(90, 20, 168));
        cbDiscount.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        cbDiscount.setForeground(new java.awt.Color(255, 255, 255));
        cbDiscount.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "5%", "10%", "20%", "25%", "40%", "50%" }));

        javax.swing.GroupLayout jPanelAddLayout = new javax.swing.GroupLayout(jPanelAdd);
        jPanelAdd.setLayout(jPanelAddLayout);
        jPanelAddLayout.setHorizontalGroup(
            jPanelAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAddLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelAddLayout.createSequentialGroup()
                        .addGroup(jPanelAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblCategory)
                            .addComponent(lblDiscount))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 193, Short.MAX_VALUE)
                        .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addGroup(jPanelAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblName, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblRange)
                            .addComponent(lblPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(7, 7, 7)
                        .addComponent(rbtnLow, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rbtnMedium)
                        .addGap(18, 18, 18)
                        .addComponent(rbtnHigh, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(jPanelAddLayout.createSequentialGroup()
                        .addComponent(lblModelNumber)
                        .addGap(30, 30, 30)
                        .addGroup(jPanelAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelAddLayout.createSequentialGroup()
                                .addComponent(cbDiscount, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanelAddLayout.createSequentialGroup()
                                .addGroup(jPanelAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanelAddLayout.createSequentialGroup()
                                        .addComponent(txtModelNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanelAddLayout.createSequentialGroup()
                                        .addComponent(cbCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txtPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(55, 55, 55))))))
        );
        jPanelAddLayout.setVerticalGroup(
            jPanelAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAddLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtModelNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblModelNumber, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCategory, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cbCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPrice, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRange, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rbtnLow)
                    .addComponent(rbtnMedium)
                    .addComponent(rbtnHigh)
                    .addComponent(cbDiscount, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDiscount, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(jPanelAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(191, 191, 191))
        );

        jMainPanel.add(jPanelAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 460, 690, 240));

        jPanelSearch.setBackground(java.awt.SystemColor.window);
        jPanelSearch.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(90, 20, 168)), "Search", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N

        jPanelSearchByItem.setBackground(java.awt.SystemColor.window);
        jPanelSearchByItem.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Search by Category", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N
        jPanelSearchByItem.setForeground(new java.awt.Color(255, 255, 255));

        cbSearchByCategory.setBackground(new java.awt.Color(90, 20, 168));
        cbSearchByCategory.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        cbSearchByCategory.setForeground(new java.awt.Color(255, 255, 255));
        cbSearchByCategory.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Keyboard", "Mouse", "Monitor", "Speaker", "Graphics Card", "RAM", "SSD", "HDD" }));

        btnSearchByCategory.setBackground(new java.awt.Color(90, 20, 168));
        btnSearchByCategory.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnSearchByCategory.setForeground(new java.awt.Color(255, 255, 255));
        btnSearchByCategory.setText("Search Applience by Category");
        btnSearchByCategory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchByCategoryActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelSearchByItemLayout = new javax.swing.GroupLayout(jPanelSearchByItem);
        jPanelSearchByItem.setLayout(jPanelSearchByItemLayout);
        jPanelSearchByItemLayout.setHorizontalGroup(
            jPanelSearchByItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSearchByItemLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelSearchByItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSearchByCategory, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cbSearchByCategory, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanelSearchByItemLayout.setVerticalGroup(
            jPanelSearchByItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSearchByItemLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cbSearchByCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(btnSearchByCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );

        jPanelSearchByPrice.setBackground(java.awt.SystemColor.window);
        jPanelSearchByPrice.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0))), "Search by Price", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N

        txtSearchByPrice.setForeground(new java.awt.Color(153, 153, 153));
        txtSearchByPrice.setText("Enter Price To Search");
        txtSearchByPrice.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtSearchByPriceFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtSearchByPriceFocusLost(evt);
            }
        });
        txtSearchByPrice.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtSearchByPriceKeyTyped(evt);
            }
        });

        btnSearchByPrice.setBackground(new java.awt.Color(90, 20, 168));
        btnSearchByPrice.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnSearchByPrice.setForeground(new java.awt.Color(255, 255, 255));
        btnSearchByPrice.setText("Search Appliance by Price");
        btnSearchByPrice.setMaximumSize(new java.awt.Dimension(199, 25));
        btnSearchByPrice.setMinimumSize(new java.awt.Dimension(199, 25));
        btnSearchByPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchByPriceActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelSearchByPriceLayout = new javax.swing.GroupLayout(jPanelSearchByPrice);
        jPanelSearchByPrice.setLayout(jPanelSearchByPriceLayout);
        jPanelSearchByPriceLayout.setHorizontalGroup(
            jPanelSearchByPriceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSearchByPriceLayout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addGroup(jPanelSearchByPriceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSearchByPrice, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSearchByPrice, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanelSearchByPriceLayout.setVerticalGroup(
            jPanelSearchByPriceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelSearchByPriceLayout.createSequentialGroup()
                .addContainerGap(36, Short.MAX_VALUE)
                .addComponent(txtSearchByPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(btnSearchByPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );

        javax.swing.GroupLayout jPanelSearchLayout = new javax.swing.GroupLayout(jPanelSearch);
        jPanelSearch.setLayout(jPanelSearchLayout);
        jPanelSearchLayout.setHorizontalGroup(
            jPanelSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSearchLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanelSearchByItem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanelSearchByPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanelSearchLayout.setVerticalGroup(
            jPanelSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSearchLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelSearchByItem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelSearchByPrice, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jMainPanel.add(jPanelSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 460, 490, 230));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(90, 20, 168));
        jLabel12.setText("info@comrade.com");
        jMainPanel.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 120, -1, -1));

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("French Script MT", 0, 30)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(90, 20, 168));
        jLabel8.setText("Tommorow Starts Here");
        jMainPanel.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 80, -1, -1));

        jBackgroundPanel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Computer_Comrade/MyApril10 1.png"))); // NOI18N
        jMainPanel.add(jBackgroundPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(-2, 0, 1210, 680));

        jMenuBar1.setBackground(new java.awt.Color(255, 255, 255));

        jMenu1.setText("File");

        miOpen.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        miOpen.setText("Open");
        miOpen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miOpenActionPerformed(evt);
            }
        });
        jMenu1.add(miOpen);

        miSave.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        miSave.setText("Save");
        miSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miSaveActionPerformed(evt);
            }
        });
        jMenu1.add(miSave);

        miImport.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_I, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        miImport.setText("Import");
        miImport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miImportActionPerformed(evt);
            }
        });
        jMenu1.add(miImport);

        miExit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        miExit.setText("Exit");
        miExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miExitActionPerformed(evt);
            }
        });
        jMenu1.add(miExit);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jMainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jLoginPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 1209, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jMainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jLoginPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 710, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void txtNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNameFocusGained
        if(txtName.getText().equals("Enter Name")) {
            txtName.setText("");
            txtName.setForeground(new Color(0,0,0));
        }
    }//GEN-LAST:event_txtNameFocusGained

    private void txtNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNameFocusLost
        if(txtName.getText().equals("")) {
            txtName.setText("Enter Name");
            txtName.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_txtNameFocusLost

    private void txtPriceFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPriceFocusGained
        if(txtPrice.getText().equals("Enter Price")) {
            txtPrice.setText("");
            txtPrice.setForeground(new Color(0,0,0));
        }
    }//GEN-LAST:event_txtPriceFocusGained

    private void txtPriceFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPriceFocusLost
        if(txtPrice.getText().equals("")) {
            txtPrice.setText("Enter Price");
            txtPrice.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_txtPriceFocusLost

    private void txtPriceKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPriceKeyTyped
        char c = evt.getKeyChar();
        if(!Character.isDigit(c)) {
            evt.consume();
        }
    }//GEN-LAST:event_txtPriceKeyTyped

    private void txtModelNumberFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtModelNumberFocusGained
        if(txtModelNumber.getText().equals("Enter Model Number")) {
            txtModelNumber.setText("");
            txtModelNumber.setForeground(new Color(0,0,0));
        }
    }//GEN-LAST:event_txtModelNumberFocusGained

    private void txtModelNumberFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtModelNumberFocusLost
        if(txtModelNumber.getText().equals("")) {
            txtModelNumber.setText("Enter Model Numberz");
            txtModelNumber.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_txtModelNumberFocusLost

    
    public void mergeSort(ArrayList<ComputerComrade> price) {
        if (price.size() <= 1) {
            return;
        }
        
        int fLength = price.size() / 2;
        int sLength = price.size() - fLength;
        ArrayList<ComputerComrade> first = new ArrayList();
        ArrayList<ComputerComrade> second = new ArrayList();
        
        for (int i = 0; i < fLength; i++) {
            first.add(price.get(i));
        }

        for (int i = 0; i < sLength; i++) {
            second.add(price.get(fLength + i));
        }
        
        mergeSort(first);
        mergeSort(second);
        merge(first, second, price);
    }

    public static void merge(ArrayList<ComputerComrade> first, ArrayList<ComputerComrade> second, ArrayList<ComputerComrade> price) {
        int a = 0;
        int b = 0;
        int j = 0;
        
        while (a < first.size() && b < second.size()) {
            if (first.get(a).getPrice() < second.get(b).getPrice()) {
                price.set(j, first.get(a));
                a++;
            }
            else {
                price.set(j, second.get(b));
                b++;
            }
            j++;
        }
        
        while (a < first.size()) {
            price.set(j, first.get(a));
            a++;
            j++;
        }

        while (b < second.size()) {
            price.set(j, second.get(b));
            b++;
            j++;
        }
    }
    
    public static int binarySearch(ArrayList<ComputerComrade> priceSearch, int low, int high, int value) {  
        int mid = (low + high)/2; 
        if (low <= high){ 
             
            if ( priceSearch.get(mid).getPrice() == value ){  
                return mid;     
            }
            
            else if ( priceSearch.get(mid).getPrice() > value ){  
                return binarySearch(priceSearch, low, mid-1, value);
            }
            
            else{  
                return binarySearch(priceSearch, mid+1, high, value); 
            }  
        }  
        
        else { 
            return -1;
        }  
    }
    
    
    private void save() {
        File file = new File("src//Computer_Comrade//data.csv");//Loading of file
        
        try (FileWriter wr = new FileWriter(file)) {
            
            if (file.isFile()) {
                file.createNewFile();
            }    
            
            for (ComputerComrade s : tData) {
                String v[] = {s.getModelNumber(), s.getName(), s.getCategory(), s.getRange(), Integer.toString(s.getPrice()), s.getDiscount()};
                
                for (int i = 0; i < v.length; i++) {
                    wr.append(v[i]);
                    if (i == v.length - 1) {
                        break;
                    }
                    wr.append(",");//CSV comma separated value
                }
                wr.append("\n");
            }
            wr.flush();
        }
        catch (IOException ex) {
            Logger.getLogger(ComputerComradeInfo.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    
    
    
    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        try {
            String modelNumber = txtModelNumber.getText().trim();
            String name = txtName.getText().trim();
            String category = (String)cbCategory.getSelectedItem();
            String rangeType;

            //selecting range from radio button
            if(rbtnLow.isSelected() == true){
                rangeType = "Low";
            }
            else if(rbtnMedium.isSelected() == true){
                rangeType = "Medium";
            }
            else {
                rangeType = "High";
            }
            String range = rangeType;

            int price = Integer.parseInt(txtPrice.getText().trim());
            String discount = (String)cbDiscount.getSelectedItem();
            boolean emptyRowFlag = false;
            
//            if (!modelNumber.equals("Enter Model Number") && !name.equals("Enter Name") && !range.equals("Enter Range") && !discount.equals("Enter Discount") && price > 0) {
//                String[] value = {modelNumber, name, category, range, Integer.toString(price), discount};
//                DefaultTableModel dfm = (DefaultTableModel) tblInfo.getModel();
//                ComputerComrade Object = new ComputerComrade (modelNumber, name, category, range, price, discount);
//                mergeSort(tData);
//                dfm.addRow(value);
//                tData.add(Object);
//                save();
//                
//            }

            if (!modelNumber.equals("Enter Model Number") && !name.equals("Enter Name") && !range.equals("Enter Range") && !discount.equals("Enter Discount") && price > 0) {
                String[] value = {modelNumber, name, category, range, Integer.toString(price), discount};
                int rowCount = tblInfo.getRowCount();
                int nextRow = 0;
                String p;

                do {
                    p = (String) tblInfo.getValueAt(nextRow, 0);
                    if (p != null && p.length() != 0) {
                        nextRow++;
                    }

                    else {
                        emptyRowFlag = true;
                    }
                }
                while (nextRow < rowCount && !emptyRowFlag);

                if (tData.size() >= 1) {

                    for (ComputerComrade n : tData) {

                        if (modelNumber.equals(n.getModelNumber())) {
                            emptyRowFlag = false;
                            JOptionPane.showMessageDialog(rootPane, "The Model Number is already in use!!", "Error!!", JOptionPane.ERROR_MESSAGE);
                            return  ;
                        }

                        else {
                            emptyRowFlag = true;
                        }
                    }
                }
                else{
                    emptyRowFlag = true;
                }

                if (emptyRowFlag) {
                    int colCount = tblInfo.getColumnCount();

                    if (nextRow < rowCount) {

                        ComputerComrade Object = new ComputerComrade(modelNumber, name, category, range, price, discount);
                        tData.add(Object);
                        mergeSort(tData);

                        for (int i = 0; i < colCount; i++) {
                            tblInfo.setValueAt(value[i], nextRow, i);
                        }
                    }
                    else {
                        JOptionPane.showMessageDialog(rootPane, "No Empty Row Found!!", "Error!!", JOptionPane.ERROR_MESSAGE);
                    }
                    save(); //calls save() method for saving the data to created file
                }
            }
            else if(price < 1){
                JOptionPane.showMessageDialog(rootPane,"Input Value Not Valid For Price." ,"Invalid Input!!", JOptionPane.ERROR_MESSAGE);
            }
            else {
                JOptionPane.showMessageDialog(rootPane, "Please Enter all the data of product", "Error!!", JOptionPane.ERROR_MESSAGE);
            }
        }
        catch (NullPointerException npe) {
            JOptionPane.showMessageDialog(rootPane, "No Data, Check Your Input Data", "Error!!", JOptionPane.ERROR_MESSAGE);
        }
        catch (NumberFormatException nfe) {
            JOptionPane.showMessageDialog(rootPane, "Error While Retrieving Inputted Data, Please Check Your Input", "Error!!", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        int result = JOptionPane.showConfirmDialog(rootPane,"Do You Want To Clear All The Text Fields?","Warning!!",JOptionPane.YES_NO_OPTION); //asks user to clear form
        if(result == 0) {
            txtModelNumber.setText("Enter Model Number");
            txtModelNumber.setForeground(new Color(153,153,153));
            txtName.setText("Enter Name");
            txtName.setForeground(new Color(153,153,153));
            cbCategory.setSelectedIndex(0);
            rbtnLow.setSelected(true);
            txtPrice.setText("Enter Price");
            txtPrice.setForeground(new Color(153,153,153));
            cbDiscount.setSelectedIndex(0);
            txtSearchByPrice.setText("Enter Price To Search");
            txtSearchByPrice.setForeground(new Color(153,153,153));
        }
        else {
            return;
        }
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnSearchByCategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchByCategoryActionPerformed
        String categorySearch = "";
        String cKey = (String)cbSearchByCategory.getSelectedItem(); //selecting key value from comboBox

        for(ComputerComrade c:tData) {
            if(c.getCategory().equals(cKey)) {
                categorySearch +=  " Model Number:"+c.getModelNumber()+"\n Name:"+c.getName()+"\n Price:"+c.getPrice()+"\n Catagory:"+c.getCategory()+"\n\n"; //printing searched values
            }
        }

        if(!categorySearch.equals("")) {
            JOptionPane.showMessageDialog(rootPane," The Item is:"+"\n" + categorySearch);
        }
        else {
            JOptionPane.showMessageDialog(rootPane,"No Data in this Category" ,"No Such Data",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnSearchByCategoryActionPerformed

    private void txtSearchByPriceFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtSearchByPriceFocusGained
        if(txtSearchByPrice.getText().equals("Enter Price To Search")) {
            txtSearchByPrice.setText("");
            txtSearchByPrice.setForeground(new Color(0,0,0));
        }
    }//GEN-LAST:event_txtSearchByPriceFocusGained

    private void txtSearchByPriceFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtSearchByPriceFocusLost
        if(txtSearchByPrice.getText().equals("")) {
            txtSearchByPrice.setText("Enter Price To Search");
            txtSearchByPrice.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_txtSearchByPriceFocusLost

    private void txtSearchByPriceKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchByPriceKeyTyped
        char c = evt.getKeyChar();
        if(!Character.isDigit(c)) {
            evt.consume();
        }
    }//GEN-LAST:event_txtSearchByPriceKeyTyped

    private void btnSearchByPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchByPriceActionPerformed
        try {

            mergeSort(tData); //calls mergeSort() andd pass the array list as parameter
            int price = Integer.parseInt(txtSearchByPrice.getText().trim()); //converts string to integer type
            int i = binarySearch(tData,0,tData.size()-1,price);

            if (i == -1) {
                JOptionPane.showMessageDialog(rootPane,"There is No Data with that Price." ,"No Any Data!!",JOptionPane.INFORMATION_MESSAGE);
            }

            else { //displaying searched details
                JOptionPane.showMessageDialog(rootPane,"\n"+" Model Number: "+tData.get(i).getModelNumber()+"\n Name: "+tData.get(i).getName()+"\n Price: "+tData.get(i).getPrice(),"Appliance Information",JOptionPane.INFORMATION_MESSAGE);
            }
        }
        catch(NumberFormatException nfe) { //exception handling
            if (txtSearchByPrice.getText().equals("Enter Price To Search")) {
                JOptionPane.showMessageDialog(rootPane,"No Any Data is Inserted." ,"Empty Text Fields!!",JOptionPane.ERROR_MESSAGE);
            }
            else {
                JOptionPane.showMessageDialog(rootPane,"Please Enter Correct Data Type" ,"Error Data Type!!",JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnSearchByPriceActionPerformed

    private void miSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miSaveActionPerformed
        // TODO add your handling code here:  
            save();
       
    }//GEN-LAST:event_miSaveActionPerformed

    private void miOpenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miOpenActionPerformed
        // TODO add your handling code here:
        try {
            File file = new File("src//Computer_Comrade//data.csv"); //sets file location
            
            if(file.exists()) {
                if(Desktop.isDesktopSupported()) {
                    Desktop.getDesktop().open(file); //Opens the previously saved file
                }
                else {
                    JOptionPane.showMessageDialog(rootPane,"Not Supported in Desktop" ,"Error!!",JOptionPane.ERROR_MESSAGE); 
                }
            }
            else {
                JOptionPane.showMessageDialog(rootPane,"File Doesn't Exists." ,"Error!!",JOptionPane.ERROR_MESSAGE);
            }
        }
        catch (Exception ex) {
            Logger.getLogger(ComputerComradeInfo.class.getName()).log(Level.SEVERE, null, ex);
        } 
    }//GEN-LAST:event_miOpenActionPerformed

    private void miImportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miImportActionPerformed
        // TODO add your handling code here:
        try {
            File selectedFile = new File("src//Computer_Comrade//data.csv");
            if(selectedFile.exists()) {
                if(selectedFile.length()==0) {
                    JOptionPane.showMessageDialog(rootPane,"There is No Previously Saved Data" ,"Error!!",JOptionPane.ERROR_MESSAGE); 
                }
                else{
                    BufferedReader br = new BufferedReader(new FileReader(selectedFile));
                    Object[] lines = br.lines().toArray();
                    int rowCount = tblInfo.getRowCount();
                    int nextRow = 0;
                    boolean emptyRowFlag = false;
                    String p;
            

                    for (int i = 0; i < lines.length; i++) {  
                        String[] row = lines[i].toString().split(",");
                        do {
                            p = (String) tblInfo.getValueAt(nextRow, 0);
                    
                            if (p != null && p.length() != 0) {
                                nextRow++;
                            } 
                    
                            else {
                                emptyRowFlag = true;
                            }
                        }
                        while (nextRow < rowCount && !emptyRowFlag);

                        if (emptyRowFlag) {
                            int colCount = tblInfo.getColumnCount();
                    
                            if (nextRow < rowCount) {

                                for (int j = 0; j < colCount; j++) {
                                    tblInfo.setValueAt(row[j], nextRow, j);
                                }
                            }
                        } 
                        else {
                            JOptionPane.showMessageDialog(rootPane, "No Empty Row Found!!", "Error!!", JOptionPane.ERROR_MESSAGE);
                        }
                    }
                }
            } 
            else{
                selectedFile.createNewFile();
                JOptionPane.showMessageDialog(rootPane,"There is No Previously Saved Data" ,"Error!!",JOptionPane.ERROR_MESSAGE); 
                return;
            }
        }
        
        catch (Exception ex) {
            Logger.getLogger(ComputerComrade.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_miImportActionPerformed

    private void txtPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPasswordActionPerformed
        // TODO ad^d your handling code here:
    }//GEN-LAST:event_txtPasswordActionPerformed

    private void txtUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsernameActionPerformed

    
    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        // TODO add your handling code here:
        
            String username = txtUsername.getText().trim();
            String password = txtPassword.getText().trim();
            if (username.equals("User") && password.equals("Password123")) {
                jLoginPanel.setVisible(false);
                jMainPanel.setVisible(true);
            }
            else {
                JOptionPane.showMessageDialog(rootPane, "Username or Password is invalid!!", "Error!!", JOptionPane.ERROR_MESSAGE);
            }
        
//        catch(NumberFormatException npe) {
//            JOptionPane.showMessageDialog(rootPane, "Username Or Password is invalid.\n TRY username: Computer_Comrade \npassword:PREM_BISHAL_YOGESH", "Error!!", JOptionPane.ERROR_MESSAGE);  
//        }
        
        
    }//GEN-LAST:event_btnLoginActionPerformed

    private void btnHintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHintActionPerformed
        // TODO add your handling code here:
          JOptionPane.showMessageDialog(rootPane,"\n Username: User \n Password: Password123", "Hint!!",1);
    }//GEN-LAST:event_btnHintActionPerformed

    private void txtPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPriceActionPerformed

    private void miExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miExitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_miExitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ComputerComradeInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ComputerComradeInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ComputerComradeInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ComputerComradeInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ComputerComradeInfo().setVisible(true);                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnHint;
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btnSearchByCategory;
    private javax.swing.JButton btnSearchByPrice;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cbCategory;
    private javax.swing.JComboBox<String> cbDiscount;
    private javax.swing.JComboBox<String> cbSearchByCategory;
    private javax.swing.JLabel jBackgroundPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jLoginPanel;
    private javax.swing.JPanel jMainPanel;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanelAdd;
    private javax.swing.JPanel jPanelSearch;
    private javax.swing.JPanel jPanelSearchByItem;
    private javax.swing.JPanel jPanelSearchByPrice;
    private javax.swing.JPanel jPanelTable;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCategory;
    private javax.swing.JLabel lblDiscount;
    private javax.swing.JLabel lblModelNumber;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblPrice;
    private javax.swing.JLabel lblRange;
    private javax.swing.JMenuItem miExit;
    private javax.swing.JMenuItem miImport;
    private javax.swing.JMenuItem miOpen;
    private javax.swing.JMenuItem miSave;
    private javax.swing.JRadioButton rbtnHigh;
    private javax.swing.JRadioButton rbtnLow;
    private javax.swing.JRadioButton rbtnMedium;
    private javax.swing.JTable tblInfo;
    private javax.swing.JTextField txtModelNumber;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPassword;
    private javax.swing.JTextField txtPrice;
    private javax.swing.JTextField txtSearchByPrice;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
